spring.main.web-application-type=none
spring.jmx.enabled=false
spring.profiles.active=local
spring.main.banner-mode=off
spring.threads.virtual.enabled=true

# API Tokens

google.books.api.key=${GOOGLE_BOOK_API_TOKEN}
hardcover.book.api.key=${HARDCOVER_TOKEN}
