#!/usr/bin/env python -B
# vi: set syntax=python ts=4 sw=4 sts=4 et ff=unix ai si :

"""
export-lbdb-data: Exports lbdb data from the database to Excel files.

Usage:
    export-lbdb-data [options]

Options:
    -a, --authors=<file>    Exported authors filename [default: authors.xlsx]
    --debug                 Enable debug mode
    -d, --directory=<path>  Directory to export files [default: .]
    -h, --help              Show this help screen
    -t, --titles=<file>     Exported titles filename. [default: titles.xlsx]
    --version               Prints the version
"""

import sqlite3
import sys
from pathlib import Path

import pandas

DATABASE: Path = Path.home() / "data" / "lbdb.db"


def main() -> None:
    export('select auth_name as "Name" from Author order by 1', Path(arguments["--directory"]) / arguments["--authors"])

    export(
        """
        select
           b.book_title as "Title", m.med_desc as "Media", group_concat(a.auth_name) as "Authors"
        from
           Book b
        join
           Media_Type m on m.med_id=b.med_id
        join
           Author_Book_Xref x on x.book_id=b.book_id
        join
           Author a on a.auth_id=x.auth_id
        group by
           b.book_title, m.med_desc
        order by
           lower(b.book_title)
        """,
        Path(arguments["--directory"]) / arguments["--titles"],
    )

    sys.exit(0)


def export(query: str, outputPath: str) -> None:
    """Exports data from the database to an Excel file."""

    # Connect and read
    with sqlite3.connect(DATABASE) as connection:
        dataFrame: pandas.DataFrame = pandas.read_sql_query(query, connection)

    # Write to Excel
    dataFrame.to_excel(outputPath, index=False)

    if arguments["--debug"]:
        print(f"Data exported successfully to {outputPath}")


if __name__ == "__main__":
    from docopt import docopt

    arguments = docopt(__doc__, version="0.0.4")
    main()
